obstacle_range: 5.0
raytrace_range: 5.0
footprint:
  - [-0.2975, 0.2500]
  - [0.2975, 0.2500]
  - [0.2975, -0.2500]
  - [-0.2975, -0.2500]
inflation_radius: 0.1
observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: laser_link
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
