odom_frame_id        : "odom"
base_frame_id        : "base_link"
global_frame_id      : "map"
laser_topic_name     : "base_scan"  # "base_scan" for stage, "scan" for gazebo
map_topic_name       : "map"
init_pose_topic_name : "initialpose"
transform_tolerance  : 0.1
#8.40 #1.0
#14.35 #1.0
initial_pose_x: 0.5
initial_pose_y : 4.5 
initial_pose_a : -1.57

initial_cov_xx : 0.1
initial_cov_yy : 0.1
initial_cov_aa : 0.1

enable_uwb : true
uwb_frame_id : "uwb"
uwb_topic_name : "uwb"
use_sim_uwb : false
uwb_correction_frequency : 20
