base_local_planner: teb_local_planner/TebLocalPlannerROS
oscillation_timeout: 5
TebLocalPlannerROS:
  acc_lim_x: 8.0
  max_vel_x: 8.0
  max_vel_x_backwards: 8.0
  acc_lim_theta: 6.28
  max_vel_theta: 6.28
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.2
  min_obstacle_dist: 0.05
  costmap_obstacles_behind_robot_dist: 0.4
